create table gui_user (
DATE_UPLOAD_FILE TIMESTAMP,
DATE_DOWNLOAD_FILE TIMESTAMP, 
USER_EMAIL varchar(100),
USER_ENABLED BOOL,
USER_PASSWORD varchar(100),
ADMIN_ENABLED BOOL,
primary key (USER_EMAIL)
);